### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by studyertomz** [TissueImageAnalytics/cerberus#19]
Hello, Simongraham. I am a medical student who has just learned Python. I followed your tutorial to complete the configuration of the environment. But I found that I wouldn't use run_infer_wsi.py. Could you please record a short how-to video as a template to guide me through your project. Thank you very much！

**Comment by Tato14** [comment]
Hi @studyertomz, it's very difficult to tell which is your actual problem here. 
Since you are using `run_infer_wsi.py` I guess you are using Whole Slides. Which ones are you using? Did you tried to use some of the TCGA svs files? You can follow this [tutorial](http://www.andrewjanowczyk.com/download-tcga-digital-pathology-images-ffpe/) to download some images. 
Also, it would be very useful to know which is exactly the error you are getting, since it would point to your actual problem.

**Comment by simongraham** [comment]
Hi @studyertomz , 

Please follow the instructions on the README:

```
# create base conda environment
conda env create -f environment.yml

# activate environment
conda activate cerberus

# install PyTorch with pip
pip install torch==1.10.1+cu102 torchvision==0.11.2+cu102 -f https://download.pytorch.org/whl/cu102/torch_stable.html
```
