### ISSUE TITLE
WSI show result

### ISSUE THREAD

**Issue by caicai2526** [TissueImageAnalytics/cerberus#27]
Dear,
how to display WSI results？I now get result output（.dat and .mat）.

**Comment by Netter99** [comment]
Hello, can you train this model successfully in local?

**Comment by simongraham** [comment]
Hi @caicai2526 

It is up to you how you want to display the results on the WSI, but we do not support visualisation as part of this repo.

Some options:
- Convert output to GeoJSON and observe in QuPath (will result in performance issues due to the number of points)
- Crop a region from the slide and grab associated annotations. Then draw contours over the region using cv2.drawContours
- Convert results to an image pyramid and use as TIAToolbox [tileserver](https://tia-toolbox.readthedocs.io/en/v1.3.1/_autosummary/tiatoolbox.visualization.tileserver.TileServer.html).
