### ISSUE TITLE
599 CRC WSIs results download

### ISSUE THREAD

**Issue by SDNAFIO** [TissueImageAnalytics/cerberus#29]
It seems like the download link for the results of the 599 CRC WSIs is missing.
Can you please provide the download link?

**Comment by simongraham** [comment]
There is a download button on the webpage as highlighted below.
<img width="783" alt="Screenshot 2023-11-26 at 19 38 22" src="https://github.com/TissueImageAnalytics/cerberus/assets/20071401/8daa085c-fd6b-4634-8164-e8b59aef3033">

Due to the size of the download, we have moved the Cerberus download to one of our secure (SFTP) sites. If you would like to download this data, please request a SFTP user account by sending an email to cerberus-support@warwick.ac.uk
